version: '3.8'

services:
  flask:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

