# Utiliser l'image Prometheus officielle
FROM prom/prometheus:v2.35.0

# Copier le fichier de configuration Prometheus
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Exposer le port Prometheus
EXPOSE 9090
